pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
include ':noiselib', ':worldengine', ':wrg_api'
project(':noiselib').projectDir = new File('../noiselib')
project(':worldengine').projectDir = new File('../worldengine')
project(':wrg_api').projectDir = new File('../api')